### ISSUE TITLE
Difference between RefCDS_human_GRCh38.p12_dNdScv.0.1.0.rda and RefCDS_human_GRCh38_GencodeV18_recommended.rda

### ISSUE THREAD

**Issue by lincj1994** [im3sanger/dndscv_data#1]
Hi. Is there any difference between RefCDS_human_GRCh38.p12_dNdScv.0.1.0.rda and RefCDS_human_GRCh38_GencodeV18_recommended.rda? Which one is recommended for cancer driver gene detection in hg38?

**Comment by im3sanger** [comment]
Hello,

Thank you. At the moment, for GRCh38 I recommend using: RefCDS_human_GRCh38_GencodeV18_recommended.rda, which is compatible with these covariates: RefCDS_human_hg19_GencodeV18_newcovariates.rda.

Instructions of how to use them can be found here:
https://github.com/im3sanger/dndscv/issues/30#issuecomment-1000868593

We are currently performing some tests and we may be able to provide slightly improved covariates in the next few days, but for now those two files are recommended.

Best,
Inigo
