### ISSUE TITLE
Error in buildref 

### ISSUE THREAD

**Issue by sakrnference** [im3sanger/dndscv_data#3]
Hi,

I followed your steps that you kindly provided and I built a transcript table for the BS000685.1 and the corresponding FASTA file too but still getting the error below. I am attaching the Reftable for BS000685.1 reference and as well here is the FASTA reference for it here.
[Reftable_ BS000685.1.txt](https://github.com/im3sanger/dndscv_data/files/8143101/Reftable_.BS000685.1.txt)

FASTA output
```
`DNAStringSet object of length 1:
    width seq                                               names               
[1] 29782 AGATCTGTTCTCTAAACGAACTT...AATTAATTTTAGTAGTGCTATCC BS000685.1 Severe...`
```
The Error  I'm getting 
```
`Error in buildref(cdsfile = cds, genomefile = fasta.data.path_test, outfile = "ouptut_refcds_test2.rda", : No chromosome names in common between the genome file and the CDS table
Traceback:`
```
can you please help me what is wrong here ?

thank you so much for all your help I really appreciate it so much

**Comment by im3sanger** [comment]
Hello,

I have answered your question in the previous thread: https://github.com/im3sanger/dndscv_data/issues/2#issuecomment-1061679626.

Best,
Inigo
